### ISSUE TITLE
UnhandledPromiseRejectionWarning in logs for a simple project

### ISSUE THREAD

**Issue by gwpantazes** [remoteinterview/zero#2]
There is a `UnhandledPromiseRejectionWarning` occurring within the logs when running a simple getting started project. The error is unexpected, and seems to not have an effect on viewing the markdown or time endpoint (it doesn't break the frontend). It also doesn't terminate the server.

To reproduce, run a zero server with the `time.js` and `index.md` files in the gist.

Zero version: zero@1.0.5

Full sample zero project found here, along with console log of the error: https://gist.github.com/gwpantazes/bf2a44e0541f29c4946c311ed8b8ca37

```
(node:1198) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type object
    at Hash.update (internal/crypto/hash.js:64:11)
    at getLambdaID (/usr/local/lib/node_modules/zero/lib/router/index.js:32:47)
    at filesUpdated.forEach (/usr/local/lib/node_modules/zero/lib/router/index.js:233:24)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/zero/lib/router/index.js:229:20
    at build (/usr/local/lib/node_modules/zero/lib/index.js:52:7)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/zero/lib/builder/index.js:76:7)
(node:1198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by asadm** [comment]
Can you check if this happens if you restart zero?

**Comment by gwpantazes** [comment]
Restarting zero appears to fix the problem. I renamed files during the zero server's runtime, which caused the unhandled promise, some apparently related `Error: ENOENT: no such file or directory`, and a 3rd Javascript type error as well.

Is renaming / hotswapping files during zero's runtime supported?

**Comment by asadm** [comment]
It definitely should be but there might be some rough edges in the file-watching code.

**Comment by muttoni** [comment]
Can confirm, same issue manifesting here as @gwpantazes and same fix works (restarting zero). Running zero@1.0.6

**Comment by abritinthebay** [comment]
Looks like the issue is the async function passed to setTimeout here:

https://github.com/remoteinterview/zero/blob/72ea1faaef51b92dbfb1f53abfcce31434258594/packages/core/lib/builder/index.js#L36

Basically you're doing `setTimeout(async () => {})) which is a problem as you have no catch block (and I'm not sure you _can_ without wrapping it)

Not quite sure you have any need for the async there (as it's going to be fired on the timeout anyhow). Simply removing that may fix it.

**Comment by abritinthebay** [comment]
If, for whatever reason, you absolutely need that to be async then you can do this:

```
const foo = async () => { // that function code };
watchDeferTimeoutID = await new Promise(resolve => resolve(setTimeout(foo, 1000)));
```

**Comment by gavocanov** [comment]
Similar stuff here, on trivial code
```js
export default (_req, res) => {
    res.send({nothingHere: true});
};
```
Start zero, put this code in a file, save it and I get: 
```js
(node:97481) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type object                           
    at Hash.update (internal/crypto/hash.js:64:11)
    at getLambdaID (/usr/local/lib/node_modules/zero/lib/router/index.js:32:47)
    at filesUpdated.forEach (/usr/local/lib/node_modules/zero/lib/router/index.js:233:24)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/zero/lib/router/index.js:229:20
    at build (/usr/local/lib/node_modules/zero/lib/index.js:52:7)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/zero/lib/builder/index.js:76:7)
(node:97481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After restarting zero it works fine.

**Comment by asadm** [comment]
I think I found the issue, 26fb60d6722bb5440778e5c3f7c69e78d2869087 should fix this. Will push a patch to npm soon.

**Comment by abritinthebay** [comment]
That might have been what was causing a specific error but that patch doesn't fix the core problem: that the setTimeout will ALWAYS have this issue if ANY code in there throws for ANY reason.

The solution I posted above is the only way you're going to fix this fully.

**Comment by abritinthebay** [comment]
to be clear the solution is as follows:

```
// note: no async
 watchDeferTimeoutID = setTimeout(() => {
    try {
        // existing code here
    } catch (err) {
         // some kind of graceful error logging here
    }
```

Anything else is just going to kick the can down the road until something else throws.
